id = "lsp-poc"
name = "Lsp POC Dev"
version = "0.1.0"
schema_version = 1
description = "POC Language Server Protocol support for Zed"
authors = ["Vasil Sokolik"]


[language_servers.zed-lsp-poc]
name = "Zed lsp POC"
language = "Markdown"
languages = [
  "Markdown",
]

[language-server.zed-lsp-poc.language_ids]
"Markdown"       = "markdown"
